services:
  - type: web
    runtime: node
    name: akshay-ranjith
    repo: https://github.com/aswinzoro99/portfolio-website-backend
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_DEFAULT_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
